### ISSUE TITLE
Ver 4.4.0 Todo

### ISSUE THREAD

**Issue by xiaoyaocz** [xiaoyaocz/biliuwp-lite#74]
Ver 4.4.0版本的待办列表，预计2022前完成(大概...)。
最新代码在dev分支。

- [ ] `Feature` 增加分享内容到动态
- [ ] `Feature` 直播默认画质调节
- [ ] `Feature` 动态支持查看视频预告
- [ ] `Feature` 动态评论展示方式修改(右侧->中间)
- [ ] `Feature` 优化发送动态
- [ ] `Feature` 支持调节小窗模式下弹幕 #39
- [ ] `Feature` 优化评论UI
- [ ] `Feature` 增加争议UP提醒
- [ ] `Feature` 动态显示最常访问
- [ ] `Feature` 动态链接可选复制及打开
- [ ] `Feature` 优化动态详情页UI
- [ ] `Feature` 增加本机历史记录
- [ ] `Feature` 音视频合并
- [ ] `Feature` 增加快捷键 (倍速、静音) #46
- [ ] `Feature` 关注列表分组 #68
- [ ] `BUG` 首页短视频无法打开 #71
- [ ] `BUG` 直播音量调节有问题
- [ ] `BUG` 新窗口浏览图片闪退
- [x] `BUG` 登录失效没有提醒
- [ ] `BUG`用户设置隐藏自己时无法进入空间
- [x] `BUG`进入直播出现错误
- [x] `BUG`优化弹幕[(NSDanmaku)](https://github.com/xiaoyaocz/NSDanmaku)
- [ ] 登录出现账号冻结 #73
- [ ] 其他问题 #7

**Comment by slinar** [comment]
加油~

**Comment by jkqxl** [comment]
之前反馈过一个分组问题，其实还有与之相关的，打开关注的人，显示的所有视频会重复显示一次的问题【严重影响使用】

**Comment by Vedmun** [comment]
鼠标中键（滚轮键）单击多标签模式下的页面（非主页）内部，会导致直接关闭该标签页。
也就是，在视频播放页按下滚轮键会关闭当前页面。Win10_21H2 当前APP版本4.3.5.0
以前的中键关闭好像只作用于标签栏上。

**Comment by a0yang** [comment]
能否加入AV1编码播放？在B站网页版，感觉CPU占用比HEVC要更低

**Comment by 1ocean1** [comment]
软件播放为啥那么暗，明显比正常的暗很多，下面有相同画面的对比图，希望能改一
![微信图片_20220426094957](https://user-images.githubusercontent.com/102215535/165203239-5a048ba2-233e-4bfe-8082-94cd80a18225.png)
下

**Comment by xiaoyaocz** [comment]
> 软件播放为啥那么暗，明显比正常的暗很多，下面有相同画面的对比图，希望能改一 ![微信图片_20220426094957](https://user-images.githubusercontent.com/102215535/165203239-5a048ba2-233e-4bfe-8082-94cd80a18225.png) 下

在播放器左侧向上滑动，可以跳转亮度

**Comment by 1ocean1** [comment]
好的，谢谢





------------------ Original ------------------
From: xiaoyaocz ***@***.***&gt;
Date: Tue,Apr 26,2022 9:53 AM
To: xiaoyaocz/biliuwp-lite ***@***.***&gt;
Cc: 1ocean1 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaoyaocz/biliuwp-lite] Ver 4.4.0 Todo (Issue #74)

**Comment by jbao-825** [comment]
右侧视频详情宽度是只支持番剧分区的视频吗？

**Comment by lzhi137** [comment]
能把广告去掉吗？
